# Generated by Django 5.0.6 on 2024-05-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Aut", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Категория петиции"),
                ),
            ],
            options={
                "verbose_name": "Категория петиции",
                "verbose_name_plural": "Категория петиции",
            },
        ),
        migrations.CreateModel(
            name="Grapic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "by_city",
                    models.ImageField(
                        blank=True, null=True, upload_to="petition_grapic"
                    ),
                ),
                (
                    "by_answer",
                    models.ImageField(
                        blank=True, null=True, upload_to="petition_grapic"
                    ),
                ),
                (
                    "by_month",
                    models.ImageField(
                        blank=True, null=True, upload_to="petition_grapic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок петиции"),
                ),
                ("description", models.TextField(verbose_name="Описание петиции")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="petition_img",
                        verbose_name="Изображение петиции",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Файл"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                        default=1,
                        max_length=15,
                    ),
                ),
                ("date_end", models.DateField(blank=True, null=True)),
                (
                    "signature_chart",
                    models.ImageField(
                        blank=True, null=True, upload_to="signature_charts/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_pet",
                        to="Aut.people",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="Petition.categorypetition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Петиция",
                "verbose_name_plural": "Петиции",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="petition_img"),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petition_images",
                        to="Petition.petition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_signature",
                        to="Aut.people",
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petition_signature",
                        to="Petition.petition",
                    ),
                ),
            ],
        ),
    ]
