# Generated by Django 5.0.6 on 2024-05-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Aut", "0001_initial"),
        ("Petition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("iin", models.CharField(max_length=12)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_chin",
                        to="Petition.categorypetition",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_chin",
                        to="Aut.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чиновник",
                "verbose_name_plural": "Чиновник",
            },
            bases=("Aut.user",),
        ),
        migrations.CreateModel(
            name="PetitionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chinov",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chinov",
                        to="Chin.chin",
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petition_answer",
                        to="Petition.petition",
                    ),
                ),
            ],
        ),
    ]
